
set ball motor1
{
    speed = 10.0
    bind_rate = 3
    bind_range = 10
    unbind_rate = 1
    diff = 0
}

set MT mt1

set tether tether1
{
    force_k = 1
}

new 1 mt1
{
    length = 500
    x = -250
    y = 0
    orientation = 0
}

new 1 tether1
{
    x = -10
    y = -20
    label = t1
}

new 1 tether1
{
    x = 10
    y = -20
    label = t2
}

new 1 motor1
{
    x = -10
    y = 0
    tethered = t1
}

new 1 motor1
{
    x = 10
    y = 0
    tethered = t2
}

